import * as z from "zod"

export const postSchema = z.object({
  /**
   * ポストの一意のID
   * @default {Generated by database}
   */
  id: z.string().uuid(),
  /**
   * ポストの内容
   */
  post: z.string().min(1).max(140),
  /**
   * ポストが作成された日時
   */
  createdAt: z.date(),
  /**
   * ポストが最後に更新された日時
   */
  updatedAt: z.date(),
})
